package payment

import (
	"errors"
	"time"

	"github.com/shopspring/decimal"
)

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "PENDING"
	PaymentStatusSuccess PaymentStatus = "SUCCESS"
	PaymentStatusFailed  PaymentStatus = "FAILED"
)

// PaymentTransaction represents the internal state of a payment
type PaymentTransaction struct {
	ID              string            `json:"id" gorm:"type:text;not null;primaryKey"`
	ReferenceNumber string            `json:"reference_number" gorm:"uniqueIndex"` // Generated by Payment Service
	TaskID          string            `json:"task_id" gorm:"index"`                // Links back to the FSM Task Node
	GatewayID       string            `json:"gateway_id" gorm:"index"`             // e.g., "lankapay"
	SessionID       string            `json:"session_id"`                          // Gateway-specific session identifier
	Amount          decimal.Decimal   `json:"amount"`
	Currency        string            `json:"currency"`       // "LKR" or foreign currency
	Status          PaymentStatus     `json:"status"`         // PENDING, SUCCESS, FAILED, EXPIRED
	PaymentMethod   string            `json:"payment_method"` // CC, BANK_TRANSFER (populated on webhook)
	ExpiryDate      time.Time         `json:"expiry_date"`
	GatewayMetadata map[string]string `json:"gateway_metadata" gorm:"serializer:json"`
	CreatedAt       time.Time         `json:"created_at"`
	UpdatedAt       time.Time         `json:"updated_at"`
}

// --------------------------------------------------------
// Gateway Session API Contracts (Outbound to GovPay)
// --------------------------------------------------------

// CreateCheckoutRequest is the payload sent to initialize a session.
type CreateCheckoutRequest struct {
	GatewayID          string            `json:"gateway_id"`
	Amount             decimal.Decimal   `json:"amount"`
	Currency           string            `json:"currency"`
	SuccessRedirectURL string            `json:"success_redirect_url,omitempty"` // Optional: User redirect on success
	CancelRedirectURL  string            `json:"cancel_redirect_url,omitempty"`  // Optional: User redirect on cancel
	ExpiresAt          time.Time         `json:"expires_at"`                     // Aligned with Task TTL
	Metadata           map[string]string `json:"metadata"`                       // Pass-through data (e.g., TaskID)
}

// validate checks that a checkout request is well-formed. now is passed in so
// the expiry check stays deterministic in tests.
func (r CreateCheckoutRequest) validate(now time.Time) error {
	if r.GatewayID == "" {
		return errors.New("gateway_id is required")
	}
	if _, ok := r.Metadata["task_id"]; !ok {
		return errors.New("task_id is required in metadata")
	}
	if !r.Amount.IsPositive() {
		return errors.New("amount must be greater than zero")
	}
	if r.Currency == "" {
		return errors.New("currency is required")
	}
	if !r.ExpiresAt.After(now) {
		return errors.New("expires_at must be in the future")
	}
	return nil
}

// CreateCheckoutResponse is the expected reply from LankaPay.
type CreateCheckoutResponse struct {
	ReferenceNumber string          `json:"reference_number"` // The generated NSW reference
	SessionID       string          `json:"session_id"`
	Type            InteractionType `json:"type"`
	CheckoutURL     string          `json:"checkout_url,omitempty"` // The hosted URL to redirect the user to
	Instructions    string          `json:"instructions,omitempty"`
	ExpiresIn       int             `json:"expires_in_seconds"`
}

// --------------------------------------------------------
// Real-Time Validation API Contracts (Inbound from GovPay)
// --------------------------------------------------------

// ValidateReferenceRequest is the payload GovPay sends when a user enters a reference in their bank app.
type ValidateReferenceRequest struct {
	PaymentReference string `json:"paymentReference"` // Maps to our ReferenceNumber
	ServiceType      string `json:"serviceType"`      // e.g., NSW_IMPORT_PERMIT_CD
}

// ValidateReferenceResponse is the payload we return to GovPay to auto-populate the user's screen.
type ValidateReferenceResponse struct {
	Amount     decimal.Decimal `json:"amount"`
	Currency   string          `json:"currency"`
	TraderName string          `json:"traderName"`
	OGAName    string          `json:"ogaName"`
	ExpiryDate string          `json:"expiryDate"` // ISO8601 format string
	IsPayable  bool            `json:"isPayable"`  // false if already paid or expired
	Remarks    string          `json:"remarks,omitempty"`
}

// --------------------------------------------------------
// Webhook and Internal Events
// --------------------------------------------------------

// The external webhook payload is defined once in the gateways package
// (gateways.WebhookPayload); gateways normalize their own status vocabulary
// into it via ParseWebhook.

type EventData struct {
	TaskID               string          `json:"task_id"`
	ReferenceNumber      string          `json:"reference_number"`
	GatewayTransactionID string          `json:"gateway_transaction_id"`
	Status               PaymentStatus   `json:"status"`
	AmountPaid           decimal.Decimal `json:"amount_paid"`
	Currency             string          `json:"currency"`
	ConfirmedAt          string          `json:"confirmed_at"`
}

// InternalPaymentEvent represents the internal event the Payment Service fires for the Task Engine.
type InternalPaymentEvent struct {
	EventType string    `json:"event_type"`
	Data      EventData `json:"data"`
}
